name: submersion
version: '1.0-SNAPSHOT'
main: fr.lhaven.submersion.Submersion
api-version: '1.21'
commands:
  creategame:
    description: "Creation de la game."
    usage: "/creategame"
  StructGen:
    description: "Creation de la game."
    usage: "/StructGen"
  structGenReload:
     description: "Recharger une structure à partir du fichier JSON."
     usage: "/<command> <NomDeStructure>"